---
development:
  # Infrastructure
  DB_FILENAME:    app/infrastructure/database/local/dev.db
  GOOGLENEWS_TOKEN:   create_googole_news_api_token
  # Application
  API_HOST: http://localhost:9000
  SESSION_SECRET: <some_secret>
app_test:
  # Infrastructure
  DB_FILENAME:    app/infrastructure/database/local/test.db
  REPOSTORE_PATH: app/infrastructure/git/repostore
test:
  DB_FILENAME: app/infrastructure/database/local/test.db
  GOOGLENEWS_TOKEN:   create_googole_news_api_token
  # Application
  API_HOST: http://localhost:9000
  SESSION_SECRET: <some_secret>

production:
  # Infrastructure
  # - assign DATABASE_URL in production
  GOOGLENEWS_TOKEN:   create_googole_news_api_token
  # Application
  API_HOST: http://url.to.app
  SESSION_SECRET: <some_secret>
