---
development:
  API_HOST: http://localhost:9090
  # Infrastructure
  DB_FILENAME:    app/infrastructure/database/local/dev.db
  GOOGLENEWS_TOKEN:   create_googole_news_api_token
  REDISCLOUD_URL: url-assigned-by-Redis-provider-on-Heroku
  AWS_ACCESS_KEY_ID: <aws credential>
  AWS_SECRET_ACCESS_KEY: <aws credential>
  AWS_REGION: <choose region>
  CLONE_QUEUE: codepraise-clone-development
  CLONE_QUEUE_URL: <set by AWS>

app_test:
  API_HOST: http://localhost:9090
  # Infrastructure
  DB_FILENAME:    app/infrastructure/database/local/test.db
  REDISCLOUD_URL: url-assigned-by-Redis-provider-on-Heroku
  AWS_ACCESS_KEY_ID: <aws credential>
  AWS_SECRET_ACCESS_KEY: <aws credential>
  AWS_REGION: <choose region>
  CLONE_QUEUE: codepraise-clone-development
  CLONE_QUEUE_URL: <set by AWS>
  
test:
  API_HOST: http://localhost:9090
  # Infrastructure
  DB_FILENAME: app/infrastructure/database/local/test.db
  GOOGLENEWS_TOKEN:   create_googole_news_api_token
  REDISCLOUD_URL: url-assigned-by-Redis-provider-on-Heroku
  AWS_ACCESS_KEY_ID: <aws credential>
  AWS_SECRET_ACCESS_KEY: <aws credential>
  AWS_REGION: <choose region>
  CLONE_QUEUE: codepraise-clone-development
  CLONE_QUEUE_URL: <set by AWS>


production:
  API_HOST: http://localhost:9090
  # Infrastructure
  # - assign DATABASE_URL in production
  GOOGLENEWS_TOKEN:   create_googole_news_api_token
  REDISCLOUD_URL: url-assigned-by-Redis-provider-on-Heroku
  AWS_ACCESS_KEY_ID: <aws credential>
  AWS_SECRET_ACCESS_KEY: <aws credential>
  AWS_REGION: <choose region>
  CLONE_QUEUE: codepraise-clone-development
  CLONE_QUEUE_URL: <set by AWS>
